name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.1.0
        with:
          lane: incrementpatch
      
