name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Install fastlane
        run: |
          brew update
          brew install fastlane
          
      - name: Run fastlane
          fastlane incrementpatch
      
